version: '2'
services:
  registry:
    container_name: docker_registry
    restart: always
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ${REGISTRY_FLD}:/var/lib/registry
  registry-ui:
   container_name: docker_registry_ui
   image: konradkleine/docker-registry-frontend:v2
   restart: always
   environment:
     VIRTUAL_HOST: '*, https://*'
     ENV_DOCKER_REGISTRY_HOST: '$DOCKER_REGISTRY'
     ENV_DOCKER_REGISTRY_PORT: 443
     ENV_DOCKER_REGISTRY_USE_SSL: 1
   links:
     - registry
   ports:
     - 127.0.0.1:5080:80
